include-and-override=portal-env.properties
upgrade.database.auto.run=true
jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://database/lportal?useUnicode=true&characterEncoding=UTF-8
jdbc.default.username=root
jdbc.default.password=
enterprise.product.notification.enabled=false
javascript.single.page.application.enabled=false
company.security.strangers=false
company.security.strangers.verify=false
company.security.update.password.required=false
users.reminder.queries.enabled=false
terms.of.use.required=false

locales.enabled=\
    ar_SA,\
    ca_ES,\
    de_DE,\
    en_US,\
    es_AR,\
    es_ES,\
    fi_FI,\
    fr_FR,\
    hu_HU,\
    ja_JP,\
    nl_NL,\
    pt_BR,\
    pt_PT,\
    sv_SE,\
    zh_CN

session.timeout=600
passwords.default.policy.change.required=false
index.on.startup=true
index.on.startup.delay=60
virtual.hosts.valid.hosts=*
admin.email.user.added.enabled=false